### PR TITLE
Refactor to use ZEIT Now (now-php)

### PR DESCRIPTION
**Pull request by f3l1x**
Hi. Here is my little refactored setup to get first working tryout.

I've felt like detective. xD 

----

Discussion on twitter https://twitter.com/jasonlong/status/1207328523289055235

### CODE REVIEW

**Comment by jasonlong** [comment]
Hey thanks @f3l1x – this is much further than I was able to get. Do you think the rest is possible or is this code just too old to be feasible?

**Comment by jasonlong** [comment]
Actually I think this might be related to the version of Stacey I’m using. I’ll try using a newer version to see if that helps.

**Comment by f3l1x** [comment]
I think the rest is possible, but with enormous time budget. I would try to upgrade Stacy app or use some newer tool for that.

I've good experience with [Hugo](https://gohugo.io/) for example.

**Comment by f3l1x** [comment]
I'm closing it here, feel free to reach me any time. I'll gladly help you. :-)

**Pull request closed without merging**
